# Generated by Django 3.2 on 2021-04-13 17:44

from django.db import migrations

import json

from swift_lyrics.models import Lyric, Album, Song


def load_initial_data(apps, schema_editor):
    json_data = open('swift_lyrics/fixtures/quotes.json')
    data = json.load(json_data)
    for d in data:
        album_name = d['album']
        song_name = d['song']
        text = d['quote']

        album = Album.objects.filter(name=album_name).first()
        if album is None:
            album = Album(name=album_name)
            album.save()

        song = Song.objects.filter(name=song_name).first()
        if song is None:
            song = Song(name=song_name, album=album)
            song.save()

        Lyric(song=song, text=text).save()
    json_data.close()


class Migration(migrations.Migration):

    dependencies = [
        ('swift_lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
